"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/componentes/Navber";
import Footer from "@/componentes/Footer";
import AuthProvider from "@/firebaseAuth/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased sm:w-10/12 sm:mx-auto`}
      >
        <AuthProvider>
          <Navber></Navber>
          <main className="px-2">
            {children}
          </main>
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
